# Generated by Django 6.0.3 on 2026-04-06 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competencia", "0002_remove_competencia_descricao"),
        ("tecnologia", "0003_remove_tecnologia_link_tecnologia_logo_and_more"),
        ("unidadeCurricular", "0002_unidadecurricular_docente_nome_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=255)),
                ("data", models.DateField()),
                ("github", models.URLField()),
                (
                    "imagem",
                    models.ImageField(blank=True, null=True, upload_to="projetos/"),
                ),
                (
                    "competencias",
                    models.ManyToManyField(blank=True, to="competencia.competencia"),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="tecnologia.tecnologia"),
                ),
                (
                    "uc",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="unidadeCurricular.unidadecurricular",
                    ),
                ),
            ],
        ),
    ]
