# Generated by Django 6.0.3 on 2026-04-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="projeto",
            name="data",
        ),
        migrations.AddField(
            model_name="projeto",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="projeto",
            name="data_inicio",
            field=models.DateField(blank=True, null=True),
        ),
    ]
