# Generated by Django 6.0.3 on 2026-04-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projeto", "0002_remove_projeto_data_projeto_data_fim_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="projeto",
            old_name="imagem",
            new_name="logo",
        ),
    ]
