# Generated by Django 6.0.3 on 2026-04-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tecnologia", "0003_remove_tecnologia_link_tecnologia_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TFC",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=255)),
                ("ano", models.IntegerField()),
                ("link", models.URLField(blank=True)),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="tecnologia.tecnologia"),
                ),
            ],
        ),
    ]
