# Generated by Django 6.0.3 on 2026-04-06 20:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tfc", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="rating",
            field=models.IntegerField(
                help_text="Classificação de 1 a 5",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="ano",
            field=models.PositiveIntegerField(),
        ),
    ]
