# Generated by Django 6.0.3 on 2026-04-06 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("perfil", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="origem",
        ),
        migrations.AddField(
            model_name="perfil",
            name="bio",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
