# Generated by Django 6.0.3 on 2026-04-06 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MakingOf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registos",
                    models.ImageField(blank=True, null=True, upload_to="makingof/"),
                ),
                ("decisoes", models.CharField(max_length=255)),
                ("erros", models.CharField(max_length=255)),
                ("justificacoes", models.CharField(max_length=255)),
                ("uso_ia", models.CharField(max_length=255)),
                (
                    "projeto",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.projeto",
                    ),
                ),
            ],
        ),
    ]
