# Generated by Django 6.0.3 on 2026-05-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="perfil",
            name="token",
        ),
        migrations.AddField(
            model_name="perfil",
            name="token_temporario",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
