# Generated by Django 6.0.3 on 2026-04-06 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competencia", "0002_remove_competencia_descricao"),
        ("perfil", "0002_remove_perfil_origem_perfil_bio"),
        ("tecnologia", "0003_remove_tecnologia_link_tecnologia_logo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Experiencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=100)),
                ("cargo", models.CharField(max_length=100)),
                ("descricao", models.CharField(max_length=255)),
                ("data_inicio", models.DateField()),
                ("data_fim", models.DateField(blank=True, null=True)),
                (
                    "competencias",
                    models.ManyToManyField(blank=True, to="competencia.competencia"),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="perfil.perfil"
                    ),
                ),
                (
                    "tecnologias",
                    models.ManyToManyField(blank=True, to="tecnologia.tecnologia"),
                ),
            ],
        ),
    ]
