# Generated by Django 6.0.3 on 2026-04-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="formacao",
            old_name="data",
            new_name="data_inicio",
        ),
        migrations.AddField(
            model_name="formacao",
            name="data_fim",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="experiencia",
            name="descricao",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="formacao",
            name="descricao",
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tfc",
            name="descricao",
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(max_length=255),
        ),
    ]
