# Generated by Django 6.0.3 on 2026-04-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "portfolio",
            "0002_rename_data_formacao_data_inicio_formacao_data_fim_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="experiencia",
            name="descricao",
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.TextField(max_length=700),
        ),
        migrations.AlterField(
            model_name="perfil",
            name="bio",
            field=models.TextField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name="projeto",
            name="descricao",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.TextField(),
        ),
    ]
