# Generated by Django 6.0.3 on 2026-04-09 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_alter_experiencia_descricao_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="experiencia",
            old_name="data_fim",
            new_name="data_de_fim",
        ),
        migrations.RenameField(
            model_name="experiencia",
            old_name="data_inicio",
            new_name="data_de_inicio",
        ),
        migrations.RenameField(
            model_name="formacao",
            old_name="data_fim",
            new_name="data_de_fim",
        ),
        migrations.RenameField(
            model_name="formacao",
            old_name="data_inicio",
            new_name="data_de_inicio",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="data_fim",
            new_name="data_de_fim",
        ),
        migrations.RenameField(
            model_name="projeto",
            old_name="data_inicio",
            new_name="data_de_inicio",
        ),
        migrations.RenameField(
            model_name="unidadecurricular",
            old_name="docente_nome",
            new_name="Nome_do_Docente",
        ),
        migrations.RenameField(
            model_name="unidadecurricular",
            old_name="docente_pagina",
            new_name="Pagina_do_Docente",
        ),
    ]
