# Generated by Django 6.0.3 on 2026-04-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_rename_data_fim_experiencia_data_de_fim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tfc",
            name="imagem",
            field=models.URLField(blank=True, null=True),
        ),
    ]
