# Generated by Django 6.0.3 on 2026-04-11 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_tfc_imagem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="makingof",
            name="projeto",
        ),
        migrations.AlterField(
            model_name="makingof",
            name="decisoes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="erros",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="justificacoes",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="makingof",
            name="uso_ia",
            field=models.TextField(),
        ),
    ]
