# Generated by Django 6.0.3 on 2026-05-14 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_tipotecnologia_tecnologia_opiniao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tfc',
            name='titulo',
            field=models.CharField(max_length=255),
        ),
    ]
