# Generated by Django 6.0.3 on 2026-04-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licenciatura", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="licenciatura",
            name="descricao",
            field=models.CharField(max_length=255),
        ),
    ]
