# Generated by Django 6.0.3 on 2026-04-06 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unidadeCurricular", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="unidadecurricular",
            name="docente_nome",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="docente_pagina",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unidadecurricular",
            name="imagem",
            field=models.ImageField(blank=True, null=True, upload_to="ucs/"),
        ),
        migrations.AlterField(
            model_name="unidadecurricular",
            name="descricao",
            field=models.CharField(max_length=255),
        ),
    ]
