# Generated by Django 6.0.3 on 2026-04-06 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("competencia", "0002_remove_competencia_descricao"),
        ("perfil", "0002_remove_perfil_origem_perfil_bio"),
    ]

    operations = [
        migrations.CreateModel(
            name="Formacao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("entidade", models.CharField(max_length=100)),
                ("data", models.DateField()),
                ("descricao", models.CharField(max_length=255)),
                (
                    "competencias",
                    models.ManyToManyField(blank=True, to="competencia.competencia"),
                ),
                (
                    "perfil",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="perfil.perfil"
                    ),
                ),
            ],
        ),
    ]
