# Generated by Django 6.0.3 on 2026-04-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnologia", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tecnologia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("descricao", models.TextField()),
                ("link", models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name="UnidadeCurricular",
        ),
    ]
