# Generated by Django 6.0.3 on 2026-04-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnologia", "0002_tecnologia_delete_unidadecurricular"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tecnologia",
            name="link",
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="tecnologias/"),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="nivel",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tecnologia",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tecnologia",
            name="descricao",
            field=models.CharField(max_length=255),
        ),
    ]
