# Generated by Django 6.0.3 on 2026-04-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tecnologia", "0003_remove_tecnologia_link_tecnologia_logo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tecnologia",
            name="nivel",
            field=models.IntegerField(
                choices=[
                    (1, "1 - Básico"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5 - Avançado"),
                ],
                help_text="Nível da tecnologia (de 1 a 5)",
                null=True,
            ),
        ),
    ]
